<? /* -*- mode: c; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
{
  $estado = array();

  $estado[ 1] = "Aguascalientes"     ;
  $estado[ 2] = "Baja Calif. Norte"  ;
  $estado[ 3] = "Baja Calif. Sur"    ;
  $estado[ 4] = "Campeche"           ;
  $estado[ 5] = "Chiapas"            ;
  $estado[ 6] = "Chihuahua"      ;
  $estado[ 7] = "Coahuila"      ;
  $estado[ 8] = "Colima"        ;
  $estado[ 9] = "D.F."          ;
  $estado[10] = "Durango"       ;
  $estado[11] = "Edo. México"   ;
  $estado[12] = "Guanajuato"    ;
  $estado[13] = "Guerrero"      ;
  $estado[14] = "Hidalgo"       ;
  $estado[15] = "Jalisco"       ;
  $estado[16] = "Michoacán"     ;
  $estado[17] = "Morelos"       ;
  $estado[18] = "Nayarit"       ;
  $estado[19] = "Nuevo León"    ;
  $estado[20] = "Oaxaca"        ;
  $estado[21] = "Puebla"         ;
  $estado[22] = "Querétaro"      ;
  $estado[23] = "Qintana Roo"    ;
  $estado[24] = "San Luis Potosí";
  $estado[25] = "Sinaloa"        ;
  $estado[26] = "Sonora"         ;
  $estado[27] = "Tabasco"        ;
  $estado[28] = "Tamaulipas"     ;
  $estado[29] = "Tlaxcala"       ;
  $estado[30] = "Veracruz"       ;
  $estado[31] = "Yucatán"        ;
  $estado[32] = "Zacatecas"      ;
}
?>

