<? /* -*- mode: c; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
if (!isset($MAXDES))
  $MAXDES = 60;

if (!isset($OBS_MAXCOLS))
  $OBS_MAXCOLS = 22;

if (!isset($OBS_MAXRENS))
  $OBS_MAXRENS = 3;

if (!isset($MAXIMPORT))
  $MAXIMPORT = 250;

if (!isset($MAXART))
  $MAXART = 40;

if (!isset($ART_MAXRENS))
  $ART_MAXRENS = 22;

if (!isset($MARGEN))
  $MARGEN = 0;

if (!isset($MARGEN))
  $MARGEN_SUP = 2;

if (!isset($tipoimp))
  $tipoimp = "EPSON";

if (!isset($DESC_MAXRENS))
  $DESC_MAXRENS = 3;

if (!isset($DESC_MAXCOLS))
  $DESC_MAXCOLS = 29;
?>
