<?  /* -*- mode: c; indent-tabs-mode: nil; c-basic-offset: 2 -*- 
 cja_web.inc  0.0.2-1. include file for OsoPOS Web.

        Copyright (C) 2000 Eduardo Israel Osorio Hernández

        Este programa es un software libre; puede usted redistribuirlo y/o
modificarlo de acuerdo con los términos de la Licencia Pública General GNU
publicada por la Free Software Foundation: ya sea en la versión 2 de la
Licencia, o (a su elección) en una versión posterior. 

        Este programa es distribuido con la esperanza de que sea útil, pero
SIN GARANTIA ALGUNA; incluso sin la garantía implícita de COMERCIABILIDAD o
DE ADECUACION A UN PROPOSITO PARTICULAR. Véase la Licencia Pública General
GNU para mayores detalles. 

        Debería usted haber recibido una copia de la Licencia Pública General
GNU junto con este programa; de no ser así, escriba a Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA02139, USA. 
*/

   $caja_web_vers =    "0.05";

   $MAXLEN_COD    =    20;
   $MAXLEN_DESC   =    50;

  $ARCHIVO_PIE_TICKET = "/etc/osopos/pie_ticket";
?>
